/* Question Wall — generated by Codex. Offline quiz from DKU_CS_Club_Quiz.docx. */
"use strict";
const questions = [
  {
    "group": "Python Output",
    "number": 1,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [1, 2]\nb = a\na += [3]\nprint(b)",
    "answer": "A. [1, 2, 3]",
    "options": [
      "[1, 2, 3]",
      "[1, 2]",
      "[3]",
      "[1, 2, 3, 3]"
    ],
    "output": "[1, 2, 3]"
  },
  {
    "group": "Python Output",
    "number": 2,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [1, 2]\nb = a\na = a + [3]\nprint(b)",
    "answer": "B. [1, 2]",
    "options": [
      "[1, 2, 3]",
      "[1, 2]",
      "[3]",
      "[]"
    ],
    "output": "[1, 2]"
  },
  {
    "group": "Python Output",
    "number": 3,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [[0] * 2] * 2\na[0][1] = 9\nprint(a)",
    "answer": "C. [[0, 9], [0, 9]]",
    "options": [
      "[[0, 9], [0, 0]]",
      "[[9, 0], [9, 0]]",
      "[[0, 9], [0, 9]]",
      "[[0, 0], [0, 9]]"
    ],
    "output": "[[0, 9], [0, 9]]"
  },
  {
    "group": "Python Output",
    "number": 4,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [1, 2]\nprint(a.append(3))",
    "answer": "D. None",
    "options": [
      "[1, 2, 3]",
      "3",
      "[3]",
      "None"
    ],
    "output": "None"
  },
  {
    "group": "Python Output",
    "number": 5,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [3, 1]\nb = a.sort()\nprint(a, b)",
    "answer": "A. [1, 3] None",
    "options": [
      "[1, 3] None",
      "[3, 1] [1, 3]",
      "[1, 3] [1, 3]",
      "[3, 1] None"
    ],
    "output": "[1, 3] None"
  },
  {
    "group": "Python Output",
    "number": 6,
    "title": "What does this program output? Choose one answer.",
    "code": "s = \"abcdef\"\nprint(s[-2:1:-2])",
    "answer": "B. ec",
    "options": [
      "eca",
      "ec",
      "ecb",
      "ce"
    ],
    "output": "ec"
  },
  {
    "group": "Python Output",
    "number": 7,
    "title": "What does this program output? Choose one answer.",
    "code": "print(list(range(5, 1, -2)))",
    "answer": "C. [5, 3]",
    "options": [
      "[5, 3, 1]",
      "[5, 4, 3, 2]",
      "[5, 3]",
      "[]"
    ],
    "output": "[5, 3]"
  },
  {
    "group": "Python Output",
    "number": 8,
    "title": "What does this program output? Choose one answer.",
    "code": "print(3 < 4 == 4)",
    "answer": "D. True",
    "options": [
      "False",
      "1",
      "TypeError",
      "True"
    ],
    "output": "True"
  },
  {
    "group": "Python Output",
    "number": 9,
    "title": "What does this program output? Choose one answer.",
    "code": "print(True + True * 2)",
    "answer": "A. 3",
    "options": [
      "3",
      "2",
      "True",
      "TypeError"
    ],
    "output": "3"
  },
  {
    "group": "Python Output",
    "number": 10,
    "title": "What does this program output? Choose one answer.",
    "code": "print({1, 2, 2} == {2, 1})",
    "answer": "B. True",
    "options": [
      "False",
      "True",
      "{1, 2}",
      "TypeError"
    ],
    "output": "True"
  },
  {
    "group": "Python Output",
    "number": 11,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [1, 2, 3]\nprint(a.pop(), a)",
    "answer": "C. 3 [1, 2]",
    "options": [
      "3 [1, 2, 3]",
      "2 [1, 3]",
      "3 [1, 2]",
      "None [1, 2]"
    ],
    "output": "3 [1, 2]"
  },
  {
    "group": "Python Output",
    "number": 12,
    "title": "What does this program output? Choose one answer.",
    "code": "def f(n):\n    return 0 if n <= 0 else n + f(n - 2)\n\nprint(f(5))",
    "answer": "D. 9",
    "options": [
      "15",
      "8",
      "RecursionError",
      "9"
    ],
    "output": "9"
  },
  {
    "group": "Python Output",
    "number": 13,
    "title": "What does this program output? Choose one answer.",
    "code": "print(7 // 2, 7 / 2, 7 % 2)",
    "answer": "A. 3 3.5 1",
    "options": [
      "3 3.5 1",
      "3 3 1",
      "3.5 3.5 1",
      "3 3.5 0"
    ],
    "output": "3 3.5 1"
  },
  {
    "group": "Python Output",
    "number": 14,
    "title": "What does this program output? Choose one answer.",
    "code": "s = \"cat\"\nprint(s.upper())\nprint(s)",
    "answer": "B. CAT\ncat",
    "options": [
      "CAT\nCAT",
      "CAT\ncat",
      "cat\ncat",
      "cat\nCAT"
    ],
    "output": "CAT\ncat"
  },
  {
    "group": "Python Output",
    "number": 15,
    "title": "What does this program output? Choose one answer.",
    "code": "x = 5\n\ndef f(x):\n    x += 1\n    return x\n\nprint(f(x), x)",
    "answer": "C. 6 5",
    "options": [
      "6 6",
      "5 5",
      "6 5",
      "5 6"
    ],
    "output": "6 5"
  },
  {
    "group": "Python Output",
    "number": 16,
    "title": "What does this program output? Choose one answer.",
    "code": "def f(x):\n    return x + 1\n\nprint(f(2) * f(3))",
    "answer": "D. 12",
    "options": [
      "7",
      "9",
      "20",
      "12"
    ],
    "output": "12"
  },
  {
    "group": "Python Output",
    "number": 17,
    "title": "What does this program output? Choose one answer.",
    "code": "d = {\"a\": 2}\nd[\"b\"] = d[\"a\"] * 2\nprint(d[\"b\"])",
    "answer": "A. 4",
    "options": [
      "4",
      "2",
      "22",
      "KeyError"
    ],
    "output": "4"
  },
  {
    "group": "Python Output",
    "number": 18,
    "title": "What does this program output? Choose one answer.",
    "code": "result = \"\"\n\nfor i in range(1, 5):\n    if i == 3:\n        continue\n    result += str(i)\n\nprint(result)",
    "answer": "B. 124",
    "options": [
      "1234",
      "124",
      "12",
      "24"
    ],
    "output": "124"
  },
  {
    "group": "Python Output",
    "number": 19,
    "title": "What does this program output? Choose one answer.",
    "code": "a = [1, 2]\nb = a[:]\na[0] = 9\nprint(a, b)",
    "answer": "C. [9, 2] [1, 2]",
    "options": [
      "[9, 2] [9, 2]",
      "[1, 2] [1, 2]",
      "[9, 2] [1, 2]",
      "[9, 2] [2]"
    ],
    "output": "[9, 2] [1, 2]"
  },
  {
    "group": "Python Output",
    "number": 20,
    "title": "What does this program output? Choose one answer.",
    "code": "n = 3\nprint(f\"{n + 1}x{n}\")",
    "answer": "D. 4x3",
    "options": [
      "{n + 1}x{n}",
      "4x{n}",
      "12",
      "4x3"
    ],
    "output": "4x3"
  },
  {
    "group": "Mission & Values",
    "number": 1,
    "title": "What motto appears at the top of the club's expo poster?",
    "options": [
      "Code Hard, Party Harder",
      "Coding the Future Together",
      "Talk Is Cheap, Show Me the Code",
      "Hello, World Forever"
    ],
    "answer": "B. Coding the Future Together"
  },
  {
    "group": "Mission & Values",
    "number": 2,
    "title": "Which trio headlines the club's identity?",
    "options": [
      "Eat. Sleep. Compile.",
      "Fork. Clone. Commit.",
      "Learn. Build. Connect.",
      "Think. Type. Deploy."
    ],
    "answer": "C. Learn. Build. Connect."
  },
  {
    "group": "Mission & Values",
    "number": 3,
    "title": "In club speak, “CS+X” means…",
    "options": [
      "Computing paired with a real-world field — finance, health, education and more",
      "Computer Science + experience points (XP)",
      "A brand-new programming language invented by the club",
      "CS majors only, plus their guests"
    ],
    "answer": "A. Computing paired with a real-world field — finance, health, education and more"
  },
  {
    "group": "Mission & Values",
    "number": 4,
    "title": "Which one has NOT been a CS+X focus area for the club?",
    "options": [
      "Finance",
      "Healthcare",
      "Education",
      "Underwater basket-weaving"
    ],
    "answer": "D. Underwater basket-weaving"
  },
  {
    "group": "Mission & Values",
    "number": 5,
    "title": "The club's mission is to grow a community that is…",
    "options": [
      "Inclusive, interdisciplinary and action-oriented",
      "Open only to elite programmers",
      "Focused on winning every leaderboard, at any cost",
      "A secret society that never meets in public"
    ],
    "answer": "A. Inclusive, interdisciplinary and action-oriented"
  },
  {
    "group": "Mission & Values",
    "number": 6,
    "title": "Which word is NOT one of the club's five action words (Learn · Build · Connect · Share · Continue)?",
    "options": [
      "Learn",
      "Build",
      "Compete",
      "Share"
    ],
    "answer": "C. Compete"
  },
  {
    "group": "Mission & Values",
    "number": 7,
    "title": "“Learning before competition” means…",
    "options": [
      "Warm up by memorising keyboard shortcuts the night before",
      "Build skills through the year so beginners aren't thrown into one stressful weekend",
      "Practice for exactly one weekend and hope for the best",
      "Only CS majors should attend prep workshops"
    ],
    "answer": "B. Build skills through the year so beginners aren't thrown into one stressful weekend"
  },
  {
    "group": "Mission & Values",
    "number": 8,
    "title": "The club's “build for people”, responsible-tech mindset cares about privacy, fairness, security, safety, accessibility and…?",
    "options": [
      "Maximising your API call quota",
      "Fitting the most features into one demo",
      "Getting to the demo first",
      "Accountability"
    ],
    "answer": "D. Accountability"
  },
  {
    "group": "Mission & Values",
    "number": 9,
    "title": "Which is NOT one of the club's guiding principles?",
    "options": [
      "CS+X",
      "“My code, my rules — never share”",
      "Inclusive participation",
      "Collaboration over ownership"
    ],
    "answer": "B. “My code, my rules — never share”"
  },
  {
    "group": "Origin & Leadership",
    "number": 10,
    "title": "In 2023, before HackDKU existed, the founding team launched…",
    "options": [
      "HackDKU 1.0",
      "Startup Weekend DKU",
      "The DKU FinTech Jam",
      "HackDuke Online at DKU"
    ],
    "answer": "D. HackDuke Online at DKU"
  },
  {
    "group": "Origin & Leadership",
    "number": 11,
    "title": "HackDuke — the club's original partner — is the flagship hackathon of which university?",
    "options": [
      "Duke",
      "MIT",
      "NYU Shanghai",
      "Zhejiang University"
    ],
    "answer": "A. Duke"
  },
  {
    "group": "Origin & Leadership",
    "number": 12,
    "title": "HackDKU was formally launched in…",
    "options": [
      "2023",
      "2025",
      "2024",
      "2026"
    ],
    "answer": "C. 2024"
  },
  {
    "group": "Origin & Leadership",
    "number": 13,
    "title": "The club's founding co-presidents (2022–23) were…",
    "options": [
      "Anar Nyambayar & Yanpei Yu",
      "Jafarbek Ulmasov & Guangzhi (Allen) Su",
      "Tianrui Gu & Kurtis",
      "Prof. Luyao Zhang & Prof. Bing Luo"
    ],
    "answer": "B. Jafarbek Ulmasov & Guangzhi (Allen) Su"
  },
  {
    "group": "Origin & Leadership",
    "number": 14,
    "title": "Which student club co-organised the very first HackDKU?",
    "options": [
      "DKU Finance Club",
      "DKU iGEM Club",
      "DKU Cheerleading Squad",
      "DKU Debate Society"
    ],
    "answer": "A. DKU Finance Club"
  },
  {
    "group": "Origin & Leadership",
    "number": 15,
    "title": "The inaugural HackDKU (March 2024) was a ____ build.",
    "options": [
      "12-hour",
      "36-hour",
      "24-hour",
      "week-long"
    ],
    "answer": "C. 24-hour"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 16,
    "title": "HackDKU 2025 stretched the format to…",
    "options": [
      "24 hours",
      "a whole week",
      "a whole month",
      "36 hours"
    ],
    "answer": "D. 36 hours"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 17,
    "title": "HackDKU 2026's central theme was…",
    "options": [
      "Blockchain everywhere",
      "The metaverse",
      "Ethics & AI",
      "Cryptocurrency mining"
    ],
    "answer": "C. Ethics & AI"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 18,
    "title": "HackDKU 2026's industry track was co-developed with…",
    "options": [
      "Luxshare",
      "Conflux",
      "KPMG",
      "L'Oréal"
    ],
    "answer": "A. Luxshare"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 19,
    "title": "Microsoft, Conflux, the Max Planck Institute and KPMG all supported HackDKU 2024. Which brand joined that list?",
    "options": [
      "Tesla",
      "Disney",
      "McDonald's",
      "L'Oréal"
    ],
    "answer": "D. L'Oréal"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 20,
    "title": "Across the HackDKU series, the club has recorded…",
    "options": [
      "30 editions and 4 teams",
      "3 editions, 70+ teams and 400+ registrations",
      "1 edition and 70,000 people",
      "400 editions and 3 people"
    ],
    "answer": "B. 3 editions, 70+ teams and 400+ registrations"
  },
  {
    "group": "HackDKU & the Innovation Challenge",
    "number": 21,
    "title": "The 2025–26 Digital Innovation Challenge wrapped up with a final showcase at…",
    "options": [
      "Duke's campus in Durham, USA",
      "A DKU dorm lounge",
      "NYU Shanghai",
      "The Shanghai Expo Centre"
    ],
    "answer": "C. NYU Shanghai"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 22,
    "title": "During the Digital Innovation Challenge, teams made a site visit to which company in Shanghai?",
    "options": [
      "ByteDance",
      "AWS",
      "Tencent Cloud",
      "Xiaomi"
    ],
    "answer": "B. AWS"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 23,
    "title": "On the 2026 WAIC field trip, students explored Ant Group, Baidu, Bilibili, Kimi/Moonshot and more. Which did they NOT visit?",
    "options": [
      "SpaceX",
      "Kunlunxin",
      "Moore Threads",
      "Google"
    ],
    "answer": "A. SpaceX"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 24,
    "title": "The club's official website lives at…",
    "options": [
      "www.dkucs.club",
      "dku-cs-club.github.io",
      "www.duke.edu/dkucs",
      "www.dkucs.com"
    ],
    "answer": "D. www.dkucs.com"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 25,
    "title": "The club's Instagram handle is…",
    "options": [
      "dku_cs_underground",
      "DKUCompSciClub",
      "hackdku_official_fanpage",
      "dkucsclub_memories"
    ],
    "answer": "B. DKUCompSciClub"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 26,
    "title": "Prof. Hai “Helen” Li gave a talk on…",
    "options": [
      "The history of the abacus",
      "Culinary robotics",
      "How to ace PE class",
      "Trustworthy & edge AI"
    ],
    "answer": "D. Trustworthy & edge AI"
  },
  {
    "group": "Trips, Talks & Finding Us",
    "number": 27,
    "title": "In Xiong Jun's career session, the “AI capability tree” was a framework for…",
    "options": [
      "Prepping for big-tech interviews",
      "Choosing a laptop",
      "Designing a dream office",
      "Ranking all-you-can-eat buffets"
    ],
    "answer": "A. Prepping for big-tech interviews"
  },
  {
    "group": "What's Next",
    "number": 28,
    "title": "Who is the club's President for 2026–27?",
    "options": [
      "Guangzhi (Allen) Su",
      "Jafarbek Ulmasov",
      "Tianrui Gu",
      "Anar Nyambayar"
    ],
    "answer": "C. Tianrui Gu"
  },
  {
    "group": "What's Next",
    "number": 29,
    "title": "The club's planned biweekly workshop pathway kicks off with…",
    "options": [
      "Advanced Blockchain Mining",
      "Photoshop for Cats",
      "The Art of Power Napping",
      "Git & Team Collaboration"
    ],
    "answer": "D. Git & Team Collaboration"
  },
  {
    "group": "What's Next",
    "number": 30,
    "title": "Which of these statements about the club is TRUE?",
    "options": [
      "You can join no matter your major or experience level",
      "CS+X connects computing with fields like health, education and design",
      "The club has run three HackDKU editions since 2024",
      "All of the above"
    ],
    "answer": "D. All of the above"
  }
];
const escapeHtml = text => String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function highlight(code){
  return code.split('\n').map((line,i)=>{
    const pattern=/("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|\b(?:def|return|if|else|for|in|continue|True|False|None)\b|\b(?:print|range|list|str)\b|\b\d+\b)/g;
    let result='',last=0;
    for(const m of line.matchAll(pattern)){
      result+=escapeHtml(line.slice(last,m.index));
      const token=m[0],kind=/^["']/.test(token)?'string':/^\d/.test(token)?'number':/^(print|range|list|str)$/.test(token)?'builtin':'keyword';
      result+=`<span class="token-${kind}">${escapeHtml(token)}</span>`;last=m.index+token.length;
    }
    return `<span class="code-line"><span class="line-number" aria-hidden="true">${i+1}</span>${result+escapeHtml(line.slice(last))}</span>`;
  }).join('');
}
const groups=[...new Set(questions.map(q=>q.group))];
const stream=document.getElementById('question-stream');
const navigation=document.getElementById('quiz-nav');
groups.forEach((group,i)=>{
  const members=questions.filter(q=>q.group===group);
  const link=document.createElement('a');
  link.href=`#q-${questions.indexOf(members[0])+1}`;
  link.className='group-link club-group';
  link.innerHTML=`<span><span class="file-icon">${String(i+1).padStart(2,'0')}</span>${escapeHtml(group)}</span><span>${members.length}</span>`;
  const grid=document.createElement('div');
  grid.className='question-grid';grid.id=`group-${i}`;grid.setAttribute('aria-label',group);
  navigation.append(link,grid);
});
questions.forEach((q,i)=>{
  const groupIndex=groups.indexOf(q.group);
  const section=document.createElement('section');section.className=q.code?'question python':'question club';section.id=`q-${i+1}`;section.setAttribute('aria-labelledby',`title-${i+1}`);
  const choices=q.options.map((v,j)=>`<li><span class="option-letter">${String.fromCharCode(65+j)}.</span><span class="${q.code?'output-option':''}">${escapeHtml(v)}</span></li>`).join('');
  const content=q.code?`<div class="editor"><div class="editor-bar"><i class="window-dot"></i><i class="window-dot"></i><i class="window-dot"></i><span class="filename">question_${String(q.number).padStart(2,'0')}.py</span><span class="language">Python 3</span></div><pre class="code"><code>${highlight(q.code)}</code></pre></div><ol class="choices python-choices">${choices}</ol>`:`<ol class="choices">${choices}</ol>`;
  section.innerHTML=`<div class="question-top"><span class="tag">${String(groupIndex+1).padStart(2,'0')} / ${escapeHtml(q.group)}</span><span class="serial">Question ${String(q.number).padStart(2,'0')} / ${q.code?20:30}</span></div><h2 id="title-${i+1}">${escapeHtml(q.title)}</h2>${content}<details class="answer"><summary>Show answer</summary><div class="answer-content"><pre class="answer-output">${escapeHtml(q.answer)}</pre></div></details><div class="question-bottom"><span>${q.code?'Think it through, then check.':'Source: DKU CS Club Quiz · Club Expo edition'}</span><span>SCROLL TO EXPLORE ↓</span></div>`;
  section.querySelector('details').addEventListener('toggle',e=>{e.target.querySelector('summary').textContent=e.target.open?'Hide answer':'Show answer';});
  stream.append(section);
  const link=document.createElement('a');link.href=`#q-${i+1}`;link.textContent=String(q.number).padStart(2,'0');link.setAttribute('aria-label',`Question ${q.number}: ${q.group}`);
  document.getElementById(`group-${groupIndex}`).append(link);
});
const sections=[...stream.children];let current=0,playing=false,timer=null,remaining=30;
const playButton=document.getElementById('play'),countdown=document.getElementById('countdown'),interval=document.getElementById('interval');
function showPosition(){
  document.getElementById('position').textContent=`${String(current+1).padStart(2,'0')} / ${questions.length}`;
  document.getElementById('section-name').textContent='PART '+(groups.indexOf(questions[current].group)+1);
  document.getElementById('progress').style.width=`${(current+1)/questions.length*100}%`;
  document.getElementById('previous').disabled=current===0;document.getElementById('next').disabled=current===questions.length-1;
  document.querySelectorAll('.question-grid a').forEach(a=>a.setAttribute('aria-current',String(a.hash===`#q-${current+1}`)));
}
function resetCountdown(){remaining=Number(interval.value);countdown.textContent=playing?`${remaining} s`:'Paused';}
function stop(){playing=false;clearInterval(timer);timer=null;playButton.textContent='▶ Autoplay';playButton.setAttribute('aria-pressed','false');resetCountdown();}
let navigationFrame=null;
let navigating=false;
function cancelNavigation(){
  if(navigationFrame!==null)cancelAnimationFrame(navigationFrame);
  navigationFrame=null;
  navigating=false;
  stream.style.scrollSnapType='';
}
function navigate(index){
  index=Math.max(0,Math.min(questions.length-1,index));
  cancelNavigation();
  current=index;showPosition();resetCountdown();
  const from=stream.scrollTop;
  const target=Math.max(0,Math.min(stream.scrollHeight-stream.clientHeight,
    from+sections[index].getBoundingClientRect().top-stream.getBoundingClientRect().top));
  if(matchMedia('(prefers-reduced-motion: reduce)').matches||Math.abs(target-from)<1){
    stream.scrollTo({top:target,behavior:'instant'});
    return;
  }
  // Keep the selected question stable while intermediate sections slide past.
  navigating=true;
  stream.style.scrollSnapType='none';
  const started=performance.now();
  function slide(now){
    const progress=Math.min(1,(now-started)/800);
    const eased=progress<0.5?4*progress**3:1-(-2*progress+2)**3/2;
    stream.scrollTo({top:from+(target-from)*eased,behavior:'instant'});
    if(progress<1)navigationFrame=requestAnimationFrame(slide);
    else cancelNavigation();
  }
  navigationFrame=requestAnimationFrame(slide);
}
// Manual scrolling can interrupt a transition immediately.
stream.addEventListener('wheel',cancelNavigation,{passive:true});
stream.addEventListener('touchstart',cancelNavigation,{passive:true});
stream.addEventListener('pointerdown',cancelNavigation,{passive:true});
function togglePlay(){
  if(playing){stop();return;}
  if(current===questions.length-1)navigate(0);
  playing=true;playButton.textContent='Ⅱ Pause';playButton.setAttribute('aria-pressed','true');resetCountdown();
  timer=setInterval(()=>{
    if(document.hidden)return;
    remaining--;countdown.textContent=`${remaining} s`;
    if(remaining<=0){if(current===questions.length-1){stop();countdown.textContent='Finished';}else navigate(current+1);}
  },1000);
}
let framePending=false;
stream.addEventListener('scroll',()=>{
  if(navigating||framePending)return;framePending=true;
  requestAnimationFrame(()=>{
    framePending=false;if(navigating)return;
    const top=stream.getBoundingClientRect().top;
    const distances=sections.map(s=>Math.abs(s.getBoundingClientRect().top-top));
    const nearest=distances.indexOf(Math.min(...distances));
    if(nearest!==current){current=nearest;showPosition();resetCountdown();}
  });
},{passive:true});
document.querySelectorAll('a[href^="#q-"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigate(Number(a.hash.slice(3))-1);}));
document.getElementById('previous').addEventListener('click',()=>navigate(current-1));
document.getElementById('next').addEventListener('click',()=>navigate(current+1));
playButton.addEventListener('click',togglePlay);interval.addEventListener('change',resetCountdown);
document.addEventListener('keydown',e=>{
  if(document.body.dataset.mode==='challenge')return;
  if(e.target.closest('input,select,textarea')||e.altKey||e.ctrlKey||e.metaKey)return;
  if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();navigate(current+1);}
  else if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();navigate(current-1);}
  else if(e.code==='Space'&&!e.target.closest('button,summary,a')){e.preventDefault();togglePlay();}
  else if(e.key.toLowerCase()==='a'){const detail=sections[current].querySelector('details');detail.open=!detail.open;}
});
const fullscreen=document.getElementById('fullscreen');
fullscreen.addEventListener('click',async()=>{
  try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}
  catch{document.getElementById('announcement').textContent='Fullscreen is unavailable. Please use your browser fullscreen command.';fullscreen.textContent='Use browser fullscreen';}
});
document.addEventListener('fullscreenchange',()=>{fullscreen.textContent=document.fullscreenElement?'Exit fullscreen ⛶':'Fullscreen ⛶';});
showPosition();
if(/^#q-\d+$/.test(location.hash))requestAnimationFrame(()=>navigate(Number(location.hash.slice(3))-1));

// Challenge state is separate from browsing; only the active question is rendered.
const challenge={status:'ready',round:[],score:0};
const challengePanel=document.getElementById('challenge-panel');
const challengeContent=document.getElementById('challenge-content');
const retryDialog=document.getElementById('retry-dialog');
retryDialog.addEventListener('close',()=>{if(challenge.status==='failed')renderChallenge();});
document.getElementById('restart-challenge').addEventListener('click',()=>{
  restartChallenge();
});
function restartChallenge(){
  challenge.status='ready';
  challenge.score=0;
  challenge.round=[];
  renderChallenge();
}
function setMode(mode){
  const isChallenge=mode==='challenge';
  if(isChallenge){stop();cancelNavigation();}else stopMatrix();
  document.body.dataset.mode=mode;
  document.getElementById('browse-panel').hidden=isChallenge;
  document.querySelector('.controls').hidden=isChallenge;
  challengePanel.hidden=!isChallenge;
  document.getElementById('browse-mode').setAttribute('aria-pressed',String(!isChallenge));
  document.getElementById('challenge-mode').setAttribute('aria-pressed',String(isChallenge));
  if(isChallenge)renderChallenge(false);
  else requestAnimationFrame(()=>navigate(current));
}
document.getElementById('browse-mode').addEventListener('click',()=>setMode('browse'));
document.getElementById('challenge-mode').addEventListener('click',()=>setMode('challenge'));
document.querySelector('.brand').addEventListener('click',()=>setMode('browse'));
function drawFive(){
  const pool=Array.from({length:questions.length},(_,i)=>i);
  for(let i=pool.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    [pool[i],pool[j]]=[pool[j],pool[i]];
  }
  return pool.slice(0,5);
}
function startChallenge(){
  // A failed attempt already has its replacement round ready.
  if(challenge.status!=='failed')challenge.round=drawFive();
  challenge.score=0;challenge.status='playing';renderChallenge();
}
function submitChallenge(value,expectedQuestion){
  if(challenge.status!=='playing'||challenge.round[challenge.score]!==expectedQuestion)return;
  const q=questions[expectedQuestion];
  const correct=value===q.answer.charAt(0);
  if(!correct){
    challenge.score=0;challenge.round=drawFive();challenge.status='failed';
    document.getElementById('streak-label').textContent='0 / 5 correct';
    document.querySelectorAll('#streak-dots span').forEach(dot=>dot.classList.remove('complete'));
    retryDialog.showModal();
    return;
  }else{
    challenge.score++;
    if(challenge.score===5)challenge.status='won';
  }
  renderChallenge();
}
let matrixPaused=false;
let matrixCleanup=()=>{};
let matrixPlayback=()=>{};
function matrixBackdrop(){
  return '<div class="matrix-field" aria-hidden="true"><canvas id="matrix-canvas"></canvas><div class="matrix-haze"></div><div class="matrix-scan"></div><div class="matrix-vignette"></div></div>';
}
function stopMatrix(){matrixCleanup();matrixCleanup=()=>{};matrixPlayback=()=>{};}
function startMatrix(){
  stopMatrix();
  if(challengePanel.hidden)return;
  const canvas=document.getElementById('matrix-canvas');
  const ctx=canvas?.getContext('2d');
  if(!ctx)return;
  const alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:;{}[]<>/';
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  let width=0,height=0,streams=[],particles=[],frame=null,last=0,elapsed=0;
  let pointer=0,parallax=0,disposed=false;
  const glyph=()=>alphabet[Math.floor(Math.random()*alphabet.length)];
  function resize(){
    width=canvas.clientWidth;height=canvas.clientHeight;
    const scale=Math.min(window.devicePixelRatio||1,2);
    canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);
    ctx.setTransform(scale,0,0,scale,0,0);
    streams=[];
    for(let layer=0;layer<3;layer++){
      const spacing=[29,43,83][layer],size=[11,15,21][layer];
      for(let x=0;x<width;x+=spacing){
        const length=9+Math.floor(Math.random()*18);
        streams.push({x:x+Math.random()*spacing,y:Math.random()*(height+size*length)-size*length,
          size,length,layer,speed:[19,38,66][layer]*(0.7+Math.random()*0.6),
          chars:Array.from({length},glyph),change:Math.random(),phase:Math.random()*Math.PI*2});
      }
    }
    particles=Array.from({length:Math.min(55,Math.floor(width/22))},()=>({x:Math.random()*width,y:Math.random()*height,size:Math.random()*1.3+0.5,speed:Math.random()*12+5}));
    paint(0);
  }
  function paint(dt){
    elapsed+=dt;parallax+=(pointer-parallax)*Math.min(1,dt*3);
    ctx.clearRect(0,0,width,height);
    for(const stream of streams){
      stream.y-=stream.speed*dt;
      if(stream.y+stream.length*stream.size*1.35<0){stream.y=height+Math.random()*150;stream.x=Math.random()*width;}
      stream.change-=dt;
      if(stream.change<0){stream.chars[Math.floor(Math.random()*stream.length)]=glyph();stream.change=0.1+Math.random()*0.3;}
      const x=stream.x+parallax*(stream.layer+1)*6;
      const centerDistance=Math.abs(x-width/2)/(width/2||1);
      const edgeWeight=0.18+0.82*Math.min(1,centerDistance*1.8);
      const pulse=0.8+0.2*Math.sin(elapsed*0.7+stream.phase);
      ctx.font=`${stream.size}px "Cascadia Code", Consolas, monospace`;
      for(let i=stream.length-1;i>=0;i--){
        const y=stream.y+i*stream.size*1.35;
        if(y< -30||y>height+30)continue;
        const fade=(1-i/stream.length)**1.8;
        ctx.globalAlpha=fade*edgeWeight*pulse*[0.22,0.52,0.72][stream.layer];
        ctx.fillStyle=i===0?'#d6fff1':i<3?'#81ffd0':stream.layer===0?'#327d78':'#32d994';
        ctx.shadowColor='#65ffd0';ctx.shadowBlur=i===0&&stream.layer>0?12:0;
        ctx.fillText(stream.chars[i],x,y);
      }
    }
    ctx.shadowBlur=0;
    for(const particle of particles){
      particle.y-=particle.speed*dt;if(particle.y<0)particle.y=height;
      ctx.globalAlpha=0.3;ctx.fillStyle='#8effd4';ctx.fillRect(particle.x,particle.y,particle.size,particle.size);
    }
    ctx.globalAlpha=1;
  }
  function tick(now){
    frame=null;if(disposed||matrixPaused||document.hidden||reduced.matches)return;
    if(!last)last=now;
    const delta=now-last;
    if(delta>=32){paint(Math.min(delta/1000,0.08));last=now;}
    frame=requestAnimationFrame(tick);
  }
  function sync(){
    if(frame!==null)cancelAnimationFrame(frame);frame=null;last=0;
    if(!disposed&&!matrixPaused&&!document.hidden&&!reduced.matches)frame=requestAnimationFrame(tick);
  }
  function move(event){if(!reduced.matches)pointer=(event.clientX-challengePanel.getBoundingClientRect().left)/(width||1)*2-1;}
  function leave(){pointer=0;}
  const observer=new ResizeObserver(resize);observer.observe(canvas);
  document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);
  challengePanel.addEventListener('pointermove',move,{passive:true});challengePanel.addEventListener('pointerleave',leave);
  matrixCleanup=()=>{
    disposed=true;if(frame!==null)cancelAnimationFrame(frame);observer.disconnect();
    document.removeEventListener('visibilitychange',sync);reduced.removeEventListener('change',sync);
    challengePanel.removeEventListener('pointermove',move);challengePanel.removeEventListener('pointerleave',leave);
  };
  matrixPlayback=sync;resize();sync();
}
function renderChallenge(focus=true){
  stopMatrix();
  const isLobby=challenge.status==='ready'||challenge.status==='failed';
  challengePanel.classList.toggle('is-lobby',isLobby);
  challengePanel.classList.toggle('matrix-paused',matrixPaused);
  document.getElementById('streak-label').textContent=`${challenge.score} / 5 correct`;
  document.getElementById('streak-dots').innerHTML=Array.from({length:5},(_,i)=>`<span class="${i<challenge.score?'complete':''}"></span>`).join('');
  if(isLobby){
    challengeContent.innerHTML=`${matrixBackdrop()}<section class="challenge-result challenge-lobby"><div class="lobby-kicker"><span class="status-dot"></span> CLUB EXPO / CHALLENGE TERMINAL</div><h1 tabindex="-1">Quiz Challenge<span class="lobby-cursor" aria-hidden="true">_</span></h1><p class="lobby-lead">Pass a five-question-quiz to win a prize!</p><p class="lobby-message ${challenge.status==='failed'?'retry-message':''}">${challenge.status==='failed'?'Try again — your streak is back to zero. A fresh set of five questions is ready.':'Get each answer right to unlock the next question. A wrong answer sends you back here for a fresh start.'}</p><button class="play-button" id="start-challenge" type="button">${challenge.status==='failed'?'Try again':'Start challenge'} →</button><button class="motion-control" id="matrix-motion" type="button" aria-pressed="${matrixPaused}">${matrixPaused?'Resume background':'Pause background'}</button></section>`;
    document.getElementById('start-challenge').addEventListener('click',startChallenge);
    document.getElementById('matrix-motion').addEventListener('click',()=>{
      matrixPaused=!matrixPaused;challengePanel.classList.toggle('matrix-paused',matrixPaused);
      matrixPlayback();
      const button=document.getElementById('matrix-motion');button.textContent=matrixPaused?'Resume background':'Pause background';button.setAttribute('aria-pressed',String(matrixPaused));
    });
  }else if(challenge.status==='won'){
    challengeContent.innerHTML='<section class="challenge-result won"><span class="result-symbol" aria-hidden="true">5 / 5</span><h1 tabindex="-1">Congratulations</h1><p>Five correct answers in a row. Challenge complete!</p><button class="play-button" id="start-challenge" type="button">Restart →</button></section>';
    document.getElementById('start-challenge').addEventListener('click',restartChallenge);
  }else{
    const questionIndex=challenge.round[challenge.score],q=questions[questionIndex];

    const codePanel=q.code?`<div class="editor"><div class="editor-bar"><span class="filename">challenge.py</span><span class="language">Python 3</span></div><pre class="code"><code>${highlight(q.code)}</code></pre></div>`:'';
    const task=codePanel+`<div class="challenge-choices ${q.code?'python-choices':''}">${q.options.map((option,i)=>`<button type="button" data-choice="${String.fromCharCode(65+i)}"><span class="option-letter">${String.fromCharCode(65+i)}.</span><span class="${q.code?'output-option':''}">${escapeHtml(option)}</span></button>`).join('')}</div>`;
    challengeContent.innerHTML=`<section class="challenge-task"><div class="question-top"><span class="tag">${escapeHtml(q.group)}</span><span class="serial">Question ${challenge.score+1} / 5</span></div><h2 tabindex="-1">${escapeHtml(q.title)}</h2>${task}</section>`;
    challengeContent.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',e=>{
      if(e.detail>1)return;
      submitChallenge(button.dataset.choice,questionIndex);
    }));

  }
  if(isLobby)startMatrix();
  if(focus){
    challengeContent.querySelector('h1,h2').focus({preventScroll:true});
    challengePanel.scrollTop=0;
  }
  document.getElementById('announcement').textContent=challenge.status==='won'?'Congratulations. Five correct answers.':challenge.status==='failed'?'Try again. Score reset to zero.':challenge.status==='playing'?`Question ${challenge.score+1} of 5. ${challenge.score} correct.`:'';
}
renderChallenge(false);
